name: Flutter CI/CD for Apple Store 

on:
  push:
    branches:
      - master
      
jobs:
  build: 
    runs-on: ubuntu-latest

    # 1) Clone repo code into the virtual environment of the workflow
    
    steps: 
      - name: Checkout code  # labels the step so it's clear in the logs
        uses: actions/checkout@v2  # actual work is done. the actions is executed

      - name: Set up Flutter
        uses: subosito/flutter-action@v6
        with:
          flutter-version: 3.10.6

      - name: Install dependencies
        run: flutter pub get
        
