name: Flutter CI/CD for Apple Store

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: 'stable'

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build release IPA
        run: flutter build ios --release
